#!/usr/bin/env python3
"""Freeze A/B fixtures from real pipeline state (Day 21).

Every fixture pairs a real task with the EXACT context string the real
context builder produces for it, so every prompt comparison — today's and every
future one — runs against byte-identical inputs.

Provenance. Two sources, both authentic, combined deliberately:

  * `architecture_doc`, `tech_stack`, and `file_list` come from real LangGraph
    checkpoints (`backend/projects.db`) of completed pipeline runs. This matters:
    the real architecture carries the three-column endpoints table with no
    response shapes (defect D7), so fixtures measure against the world the coders
    actually see, not an idealised one.
  * `generated_files` are seeded with the REAL coder output from
    `outputs/day18-fullphase` / `day19-fullphase`, so a dependent file's context
    contains genuine dependency bodies rather than invented ones.

The task lists mirror the Day 18/19 phase runs. Those runs used hand-written
plan fixtures that were never committed, so the plans here are reconstructed to
match the trees the outputs prove existed.

STALENESS: these fixtures embed today's architecture style. Task 5 sharpens the
architecture prompt, which will make them measure against a world that no longer
exists — re-freeze before the next tuning session.

Usage:  python3 scripts/freeze_fixtures.py
"""
import json
import os
import sqlite3
import sys

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BACKEND_DIR)
REPO_ROOT = os.path.dirname(BACKEND_DIR)
FIXTURE_DIR = os.path.join(BACKEND_DIR, "tests", "fixtures", "prompt_tuning")

NOTES_THREAD = "113cf67c-8c63-4713-bcc8-a5dd34e0b9d9"      # NotesTags, completed
FREELANCE_THREAD = "f1a063f8-f61f-4cbb-86c4-a825640ae552"  # FreelanceInvoicer, completed

FE_PKGS = ["react", "react-dom", "react-router-dom", "axios", "prop-types"]

# The Day 18 frontend tree, proved by outputs/day18-fullphase.
DAY18_TREE = [
    "frontend/src/App.jsx",
    "frontend/src/pages/NotesPage.jsx",
    "frontend/src/components/Header.jsx",
    "frontend/src/components/NoteCard.jsx",
    "frontend/src/components/NoteForm.jsx",
    "frontend/src/components/NoteList.jsx",
    "frontend/src/components/EmptyState.jsx",
    "frontend/src/components/TagFilter.jsx",
    "frontend/src/hooks/useNotes.js",
    "frontend/src/lib/api.js",
    "frontend/src/lib/formatDate.js",
]

DAY19_TREE = [
    "backend/app/main.py", "backend/app/database.py", "backend/app/config.py",
    "backend/app/models/note.py", "backend/app/models/tag.py",
    "backend/app/schemas/note.py", "backend/app/schemas/tag.py",
    "backend/app/routers/notes.py", "backend/app/routers/tags.py",
]


def load_checkpoint(thread_id):
    from langgraph.checkpoint.sqlite import SqliteSaver
    conn = sqlite3.connect(os.path.join(BACKEND_DIR, "projects.db"), check_same_thread=False)
    cp = SqliteSaver(conn).get({"configurable": {"thread_id": thread_id}})
    if not cp:
        raise SystemExit(f"no checkpoint for thread {thread_id}")
    return cp["channel_values"]


def seed_generated(run_dir, paths):
    """Real coder output from a Day 18/19 run, keyed by planned filepath."""
    out = {}
    for p in paths:
        disk = os.path.join(REPO_ROOT, "outputs", run_dir, p)
        if os.path.exists(disk):
            with open(disk) as f:
                # Strip the generator's header comment so the fixture holds the
                # same content the coder had in state, not the on-disk form.
                body = f.read()
            body = "\n".join(l for l in body.splitlines()
                             if "Generated by MultiAgent Builder" not in l).lstrip("\n")
            out[p] = body
    return out


def task(tid, filepath, description, requires=(), phase="frontend"):
    return {"id": tid, "filepath": filepath, "description": description,
            "requires": list(requires), "phase": phase}


def build_fixtures():
    notes = load_checkpoint(NOTES_THREAD)
    free = load_checkpoint(FREELANCE_THREAD)

    fe_files = seed_generated("day18-fullphase", DAY18_TREE)
    be_files = seed_generated("day19-fullphase", DAY19_TREE)

    # ── frontend plan mirroring the Day 18 phase run ────────────────────────
    fe_plan = [
        task("fe_api", "frontend/src/lib/api.js", "Shared axios client reading VITE_API_URL"),
        task("fe_fmt", "frontend/src/lib/formatDate.js",
             "Format an ISO timestamp as a short human-readable date string"),
        task("fe_header", "frontend/src/components/Header.jsx",
             "App header showing the title and the current note count"),
        task("fe_form", "frontend/src/components/NoteForm.jsx",
             "Form to create a note with title, body and tags", ["fe_api"]),
        task("fe_card", "frontend/src/components/NoteCard.jsx",
             "Render a single note with its tags and a delete control",
             ["fe_api", "fe_fmt"]),
        task("fe_list", "frontend/src/components/NoteList.jsx",
             "Render the list of notes", ["fe_card"]),
        task("fe_hook", "frontend/src/hooks/useNotes.js",
             "Hook owning notes state and all note API calls", ["fe_api"]),
        task("fe_page", "frontend/src/pages/NotesPage.jsx",
             "Notes page composing the header, form and list",
             ["fe_hook", "fe_form", "fe_list", "fe_header"]),
    ]
    fe_state = {
        "architecture_doc": notes["architecture_doc"],
        "tech_stack": notes["tech_stack"],
        "implementation_plan": json.dumps(fe_plan),
        "file_list": DAY18_TREE,
        "generated_files": fe_files,
    }

    # The same page task as the real NotesTags planner emitted it: requires=[].
    # This is the 17%-wired case — the truth is absent from context entirely.
    fe_state_unwired = dict(fe_state)
    fe_plan_unwired = [dict(t, requires=[]) if t["id"] == "fe_page" else t for t in fe_plan]
    fe_state_unwired["implementation_plan"] = json.dumps(fe_plan_unwired)

    # ── backend plan mirroring the Day 19 phase run ─────────────────────────
    be_plan = [
        task("be_schema_note", "backend/app/schemas/note.py",
             "Pydantic v2 schemas for the note resource", [], "backend"),
        task("be_router_notes", "backend/app/routers/notes.py",
             "FastAPI router implementing the note endpoints",
             ["be_schema_note"], "backend"),
    ]
    be_state = {
        "architecture_doc": notes["architecture_doc"],
        "tech_stack": notes["tech_stack"],
        "implementation_plan": json.dumps(be_plan),
        "file_list": DAY19_TREE,
        "generated_files": be_files,
    }

    # Child signatures taken from the REAL Day 18 output, so props_match scores
    # against the contracts that actually existed.
    child_sigs = {"NoteForm": ["onCreate"], "Header": ["noteCount"],
                  "NoteList": ["notes", "onDelete"]}

    api_paths = ["/api/notes", "/api/tags", "/notes", "/tags"]

    specs = [
        # D5 — unresolvable imports. NoteCard is the canonical case: the plan
        # itself hands it a CSS dependency the prompt forbids importing.
        dict(name="fe_notecard", agent_type="frontend_code", state=fe_state,
             task_id="fe_card",
             checks=["no_fences", "min_lines", "imports_resolve", "no_css_import",
                     "has_default_export", "guards_api_data", "endpoints_subset"],
             extra=dict(allowed_packages=FE_PKGS, file_tree=DAY18_TREE,
                        allowed_endpoints=api_paths)),
        # D5 — a pure util with no legitimate package need; the Day 18 output
        # invented `intl` / `intl-datetimeformat`.
        dict(name="fe_formatdate", agent_type="frontend_code", state=fe_state,
             task_id="fe_fmt",
             checks=["no_fences", "min_lines", "imports_resolve", "no_css_import"],
             extra=dict(allowed_packages=FE_PKGS, file_tree=DAY18_TREE, min_lines=3)),
        # D2 — the seam, WITH the planner wiring its dependencies (truth present).
        dict(name="fe_notespage", agent_type="frontend_code", state=fe_state,
             task_id="fe_page",
             checks=["no_fences", "min_lines", "imports_resolve", "no_css_import",
                     "has_default_export", "props_match", "guards_api_data"],
             extra=dict(allowed_packages=FE_PKGS, file_tree=DAY18_TREE,
                        child_signatures=child_sigs)),
        # D2 — the SAME task as the real planner emitted it (requires=[]), so the
        # truth is absent from context. Only a context-builder change can move this.
        dict(name="fe_notespage_unwired", agent_type="frontend_code",
             state=fe_state_unwired, task_id="fe_page",
             checks=["no_fences", "min_lines", "imports_resolve",
                     "has_default_export", "props_match"],
             extra=dict(allowed_packages=FE_PKGS, file_tree=DAY18_TREE,
                        child_signatures=child_sigs)),
        # D6 + D11 — backend rule adherence.
        dict(name="be_router_notes", agent_type="backend_code", state=be_state,
             task_id="be_router_notes",
             checks=["no_fences", "min_lines", "py_compile",
                     "no_schema_redefinition", "no_pep604_union",
                     "uses_session_dependency"],
             extra=dict(file_tree=DAY19_TREE)),
        dict(name="be_schema_note", agent_type="backend_code", state=be_state,
             task_id="be_schema_note",
             checks=["no_fences", "min_lines", "py_compile", "no_pep604_union"],
             extra=dict(file_tree=DAY19_TREE)),
    ]
    return specs


def freeze_all():
    from app.agents.context_builder import build_file_context

    os.makedirs(FIXTURE_DIR, exist_ok=True)
    for spec in build_fixtures():
        state = dict(spec["state"])
        state["log"] = []
        plan = json.loads(state["implementation_plan"])
        t = next(x for x in plan if x["id"] == spec["task_id"])
        phase = "backend" if spec["agent_type"] == "backend_code" else "frontend"
        prefix = "backend" if phase == "backend" else "frontend/src"
        context = build_file_context(t, state, phase_prefix=prefix, phase=phase)

        fx = {
            "name": spec["name"],
            "agent_type": spec["agent_type"],
            "provenance": ("architecture/tech_stack from checkpoint "
                           f"{NOTES_THREAD[:8]}; dependency bodies from real "
                           "Day 18/19 coder output"),
            "task": t,
            "context": context,
            "checks": spec["checks"],
            # state kept so --rebuild-context can A/B a context_builder change.
            "state": state,
        }
        fx.update(spec["extra"])
        path = os.path.join(FIXTURE_DIR, spec["name"] + ".json")
        with open(path, "w") as f:
            json.dump(fx, f, indent=2)
        print(f"  froze {spec['name']:24s} context={len(context):5d} chars  "
              f"checks={len(spec['checks'])}")
    print(f"\n{len(build_fixtures())} fixtures -> {FIXTURE_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(freeze_all())
