"""Deterministic backend infrastructure files (Day 19, ponytail #3).

config.py, database.py, main.py, and requirements.txt are boilerplate that MUST
be correct — a hallucinated dependency version breaks `pip install` for the whole
project, and a wrong session/engine setup breaks every request. So these are
rendered from hand-maintained templates and a curated version map, NOT generated
by the LLM.

Ownership: the backend coder owns these Python infra files; the DevOps agent
keeps Docker/CI; the database agent keeps Alembic migrations (no duplicate
ownership). main.py is derived from the ACTUAL generated router files, so a
router that failed to generate is never registered.
"""
import ast
import json
import os


# Curated known-good, real, installable versions for the core FastAPI stack and
# common companions. The LLM never invents a version — a confident hallucinated
# pin fails `pip install` for the entire project.
#
# ponytail: hand-maintained map, refresh periodically (Day 30 roadmap marker).
# Verified as of 2026-01. Keys are PyPI package names; values are exact pins.
KNOWN_GOOD_VERSIONS = {
    "fastapi": "0.115.6",
    "uvicorn[standard]": "0.34.0",
    "sqlalchemy": "2.0.36",
    "pydantic": "2.10.4",
    "pydantic-settings": "2.7.1",
    "alembic": "1.14.0",
    "python-dotenv": "1.0.1",
    "psycopg2-binary": "2.9.10",
    "asyncpg": "0.30.0",
    "passlib[bcrypt]": "1.7.4",
    "bcrypt": "4.2.1",
    "python-jose[cryptography]": "3.3.0",
    "pyjwt": "2.10.1",
    "email-validator": "2.2.0",
    "python-multipart": "0.0.20",
    "httpx": "0.28.1",
}

# Top-level import name -> PyPI package (as keyed in KNOWN_GOOD_VERSIONS) when
# they differ. Imports not listed here map to themselves.
_IMPORT_TO_PACKAGE = {
    "jose": "python-jose[cryptography]",
    "jwt": "pyjwt",
    "dotenv": "python-dotenv",
    "psycopg2": "psycopg2-binary",
    "pydantic_settings": "pydantic-settings",
    "passlib": "passlib[bcrypt]",
    "email_validator": "email-validator",
    "multipart": "python-multipart",
}

# Enough stdlib names to avoid mislabelling them as third-party on Python 3.9
# (which lacks sys.stdlib_module_names). Anything unknown falls through to an
# unpinned line + warning, which is the safe direction.
_STDLIB = {
    "os", "sys", "typing", "datetime", "uuid", "json", "collections", "pathlib",
    "enum", "decimal", "functools", "contextlib", "abc", "asyncio", "logging",
    "secrets", "hashlib", "time", "re", "math", "random", "base64", "io",
    "itertools", "dataclasses", "string", "warnings", "traceback", "operator",
}
_LOCAL_ROOTS = {"app", "backend"}
# The core stack is always required regardless of what the generated files import.
_ALWAYS = ["fastapi", "uvicorn[standard]", "sqlalchemy", "pydantic", "pydantic-settings"]


def _top_level_imports(code: str) -> set:
    """Third-party top-level import names in one Python file (best effort)."""
    names = set()
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return names
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                names.add(a.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            names.add(node.module.split(".")[0])
    return names


def render_requirements(tech_stack_str: str, generated_files: dict) -> tuple:
    """Deterministically render requirements.txt. Returns (content, warnings).

    Core stack is always pinned. Third-party imports detected across generated
    files are pinned from KNOWN_GOOD_VERSIONS; anything unknown gets an UNPINNED
    line and a warning — never a fabricated version.
    """
    imports = set()
    for path, content in (generated_files or {}).items():
        if path.endswith(".py"):
            imports |= _top_level_imports(content)

    warnings = []
    pinned = {pkg: KNOWN_GOOD_VERSIONS[pkg] for pkg in _ALWAYS}
    unpinned = []

    # Postgres driver if the stack asks for it.
    stack_blob = (tech_stack_str or "").lower()
    if "postgres" in stack_blob or "postgresql" in stack_blob:
        pinned["psycopg2-binary"] = KNOWN_GOOD_VERSIONS["psycopg2-binary"]

    for name in sorted(imports):
        if name in _STDLIB or name in _LOCAL_ROOTS:
            continue
        pkg = _IMPORT_TO_PACKAGE.get(name, name)
        if pkg in {p.split("[")[0] for p in _ALWAYS} or pkg in pinned:
            continue
        if pkg in KNOWN_GOOD_VERSIONS:
            pinned[pkg] = KNOWN_GOOD_VERSIONS[pkg]
        else:
            unpinned.append(pkg)
            warnings.append(
                f"requirements.txt: `{pkg}` (imported as `{name}`) is not in the "
                f"known-good version map — left unpinned; verify the correct version"
            )

    lines = [
        "# Generated by MultiAgent Builder — pinned from a curated known-good map",
        "# (versions verified 2026-01; refresh periodically). Unpinned lines are",
        "# third-party imports with no known-good pin — verify before deploying.",
    ]
    for pkg in sorted(pinned):
        lines.append(f"{pkg}=={pinned[pkg]}")
    for pkg in sorted(set(unpinned)):
        lines.append(f"{pkg}  # unpinned: not in known-good map, verify version")
    return "\n".join(lines) + "\n", warnings


def render_config() -> str:
    return '''from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application settings, loaded from environment / .env."""

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    # SQLite by default; set DATABASE_URL to a Postgres URL in production, e.g.
    # postgresql+psycopg2://user:pass@host:5432/dbname
    database_url: str = "sqlite:///./app.db"
    cors_origins: str = "*"
    secret_key: str = "change-me-in-production"


settings = Settings()
'''


def render_database() -> str:
    return '''from collections.abc import Generator

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.config import settings

# SQLite needs check_same_thread=False for FastAPI's threaded request handling;
# a Postgres URL uses no special connect args.
_connect_args = (
    {"check_same_thread": False} if settings.database_url.startswith("sqlite") else {}
)
engine = create_engine(settings.database_url, connect_args=_connect_args, pool_pre_ping=True)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


class Base(DeclarativeBase):
    """Shared declarative base — every ORM model subclasses this."""


def get_db() -> Generator[Session, None, None]:
    """FastAPI dependency yielding a database session, closed after the request."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
'''


def _router_module(filepath: str) -> str:
    """`backend/app/routers/invoices.py` -> `app.routers.invoices`."""
    from .import_fixer import _module_of
    return _module_of(filepath) or ""


def render_main(project_name: str, router_filepaths: list) -> str:
    """Render main.py registering ONLY the given (successfully generated) routers.

    Each router module is expected to expose `router = APIRouter(...)`.
    """
    imports = []
    includes = []
    for fp in router_filepaths:
        mod = _router_module(fp)
        if not mod:
            continue
        alias = mod.replace(".", "_") + "_router"
        imports.append(f"from {mod} import router as {alias}")
        includes.append(f"app.include_router({alias})")

    imports_block = "\n".join(imports) if imports else "# (no routers were generated)"
    includes_block = "\n".join(includes) if includes else "# (no routers to register)"
    title = json.dumps(project_name or "Generated API")

    return f'''from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.config import settings
from app.database import Base, engine
{imports_block}

app = FastAPI(title={title})


@app.on_event("startup")
def _create_tables() -> None:
    """Create the SQLite schema on first boot.

    WHY this exists: the shipped default is `sqlite:///./app.db` and nothing
    else creates the schema, so without this the app starts cleanly and then
    fails every request with "no such table" — the worst shape of broken,
    because /health passes and the failure only appears on real use.

    Importing app.models is what populates Base.metadata: the generated package
    marker re-exports every model class, so this one import registers all of
    them. Without it create_all runs against an empty metadata and silently
    creates nothing.

    SQLITE ONLY, deliberately. create_all cannot alter an existing table, so on
    a real database it would quietly diverge from the models the moment a column
    changes. Postgres deployments use the generated Alembic migrations instead —
    this is the zero-setup path for running the project locally, not a migration
    strategy.
    """
    if not settings.database_url.startswith("sqlite"):
        return
    try:
        import app.models  # noqa: F401 — import registers models on Base.metadata
    except ImportError:
        pass               # a project with no ORM models has no schema to create
    Base.metadata.create_all(bind=engine)

_origins = ["*"] if settings.cors_origins == "*" else [o.strip() for o in settings.cors_origins.split(",")]
app.add_middleware(
    CORSMiddleware,
    allow_origins=_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

{includes_block}


@app.get("/health", tags=["health"])
async def health():
    return {{"status": "ok"}}
'''


# ── Deterministic package markers (token audit, 2026-08-10) ──────────────────
# The frozen TodoSimple plan spends 11 of 96 tasks on `__init__.py` files —
# each a full LLM call carrying the ~2.6k-token coder preamble to produce a
# near-empty file (~29k prompt tokens per run, on the scarce pool). A package
# marker is not judgement work: like main.py above, the correct content is
# DERIVABLE from what was actually generated. An LLM __init__ can hallucinate
# re-exports of names that do not exist; a derived one cannot.
#
# Re-exports cover the one import shape the AST import fixer leaves untouched:
# `from app.models import Note` resolves `app.models` as a known package and
# is never rewritten, so it silently depends on __init__ content. Deriving
# `from .note import Note` for every class that really exists makes both
# import shapes work by construction.

def _top_level_classes(code: str) -> list:
    """Top-level class names of one module, in order; [] when unparseable
    (a failure stub or broken file must not break the package marker)."""
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return []
    return [n.name for n in tree.body if isinstance(n, ast.ClassDef)]


def render_package_inits(init_filepaths: list, generated_files: dict) -> list:
    """[(filepath, content)] for the plan's __init__.py tasks, derived from the
    package's ACTUAL generated modules. Deterministic: sorted modules, first
    definition wins on a (pathological) cross-module name collision."""
    out = []
    for init_path in sorted(init_filepaths or []):
        pkg_dir = init_path.rsplit("/", 1)[0]
        lines = []
        exported = set()
        modules = sorted(
            p for p in generated_files
            if p.rsplit("/", 1)[0] == pkg_dir and p.endswith(".py")
            and not p.endswith("__init__.py"))
        for mod_path in modules:
            mod = mod_path.rsplit("/", 1)[-1][:-3]
            names = [n for n in _top_level_classes(generated_files[mod_path])
                     if n not in exported]
            if names:
                exported.update(names)
                lines.append(f"from .{mod} import {', '.join(names)}")
        body = ("\n".join(lines) + "\n") if lines else ""
        out.append((init_path,
                    '"""Package marker (generated deterministically; re-exports '
                    'derived from the package\'s modules)."""\n' + body))
    return out


def write_package_inits(init_filepaths: list, generated_files: dict, *,
                        project_id: str, phase: str, agent_name: str,
                        log: list, errors: list) -> int:
    """Render + write the package markers, mirroring the infra write path
    (disk + generated_files + log + file_written broadcast). Returns count
    written. Never offered to the QA stream — there is nothing to review."""
    from app.core.connection_manager import manager
    from app.utils.file_writer import write_project_file

    written = 0
    for filepath, content in render_package_inits(init_filepaths, generated_files):
        result = write_project_file(project_id, filepath, content)
        if result["success"]:
            generated_files[filepath] = content
            written += 1
            log.append(f"{agent_name}: wrote package marker {filepath} (deterministic)")
            manager.broadcast_sync(project_id, {
                "type": "file_written", "filename": "__init__.py",
                "filepath": filepath, "phase": phase, "task_id": "infra",
            })
        else:
            errors.append(f"{agent_name}: failed to write {filepath}: {result['error']}")
    return written


def llm_generates_inits() -> bool:
    """Escape hatch: LLM_INIT_FILES=true restores LLM-generated __init__.py.
    Exists so the old behaviour is one env var away if a stack ever genuinely
    needs authored package markers; default is the deterministic path."""
    return os.getenv("LLM_INIT_FILES", "").lower() in ("true", "1", "yes")
