"""Deterministic backend infrastructure files (Day 19, ponytail #3).

config.py, database.py, main.py, and requirements.txt are boilerplate that MUST
be correct — a hallucinated dependency version breaks `pip install` for the whole
project, and a wrong session/engine setup breaks every request. So these are
rendered from hand-maintained templates and a curated version map, NOT generated
by the LLM.

Ownership: the backend coder owns these Python infra files; the DevOps agent
keeps Docker/CI; the database agent keeps Alembic migrations (no duplicate
ownership). main.py is derived from the ACTUAL generated router files, so a
router that failed to generate is never registered.
"""
import ast
import json


# Curated known-good, real, installable versions for the core FastAPI stack and
# common companions. The LLM never invents a version — a confident hallucinated
# pin fails `pip install` for the entire project.
#
# ponytail: hand-maintained map, refresh periodically (Day 30 roadmap marker).
# Verified as of 2026-01. Keys are PyPI package names; values are exact pins.
KNOWN_GOOD_VERSIONS = {
    "fastapi": "0.115.6",
    "uvicorn[standard]": "0.34.0",
    "sqlalchemy": "2.0.36",
    "pydantic": "2.10.4",
    "pydantic-settings": "2.7.1",
    "alembic": "1.14.0",
    "python-dotenv": "1.0.1",
    "psycopg2-binary": "2.9.10",
    "asyncpg": "0.30.0",
    "passlib[bcrypt]": "1.7.4",
    "bcrypt": "4.2.1",
    "python-jose[cryptography]": "3.3.0",
    "pyjwt": "2.10.1",
    "email-validator": "2.2.0",
    "python-multipart": "0.0.20",
    "httpx": "0.28.1",
}

# Top-level import name -> PyPI package (as keyed in KNOWN_GOOD_VERSIONS) when
# they differ. Imports not listed here map to themselves.
_IMPORT_TO_PACKAGE = {
    "jose": "python-jose[cryptography]",
    "jwt": "pyjwt",
    "dotenv": "python-dotenv",
    "psycopg2": "psycopg2-binary",
    "pydantic_settings": "pydantic-settings",
    "passlib": "passlib[bcrypt]",
    "email_validator": "email-validator",
    "multipart": "python-multipart",
}

# Enough stdlib names to avoid mislabelling them as third-party on Python 3.9
# (which lacks sys.stdlib_module_names). Anything unknown falls through to an
# unpinned line + warning, which is the safe direction.
_STDLIB = {
    "os", "sys", "typing", "datetime", "uuid", "json", "collections", "pathlib",
    "enum", "decimal", "functools", "contextlib", "abc", "asyncio", "logging",
    "secrets", "hashlib", "time", "re", "math", "random", "base64", "io",
    "itertools", "dataclasses", "string", "warnings", "traceback", "operator",
}
_LOCAL_ROOTS = {"app", "backend"}
# The core stack is always required regardless of what the generated files import.
_ALWAYS = ["fastapi", "uvicorn[standard]", "sqlalchemy", "pydantic", "pydantic-settings"]


def _top_level_imports(code: str) -> set:
    """Third-party top-level import names in one Python file (best effort)."""
    names = set()
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return names
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                names.add(a.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            names.add(node.module.split(".")[0])
    return names


def render_requirements(tech_stack_str: str, generated_files: dict) -> tuple:
    """Deterministically render requirements.txt. Returns (content, warnings).

    Core stack is always pinned. Third-party imports detected across generated
    files are pinned from KNOWN_GOOD_VERSIONS; anything unknown gets an UNPINNED
    line and a warning — never a fabricated version.
    """
    imports = set()
    for path, content in (generated_files or {}).items():
        if path.endswith(".py"):
            imports |= _top_level_imports(content)

    warnings = []
    pinned = {pkg: KNOWN_GOOD_VERSIONS[pkg] for pkg in _ALWAYS}
    unpinned = []

    # Postgres driver if the stack asks for it.
    stack_blob = (tech_stack_str or "").lower()
    if "postgres" in stack_blob or "postgresql" in stack_blob:
        pinned["psycopg2-binary"] = KNOWN_GOOD_VERSIONS["psycopg2-binary"]

    for name in sorted(imports):
        if name in _STDLIB or name in _LOCAL_ROOTS:
            continue
        pkg = _IMPORT_TO_PACKAGE.get(name, name)
        if pkg in {p.split("[")[0] for p in _ALWAYS} or pkg in pinned:
            continue
        if pkg in KNOWN_GOOD_VERSIONS:
            pinned[pkg] = KNOWN_GOOD_VERSIONS[pkg]
        else:
            unpinned.append(pkg)
            warnings.append(
                f"requirements.txt: `{pkg}` (imported as `{name}`) is not in the "
                f"known-good version map — left unpinned; verify the correct version"
            )

    lines = [
        "# Generated by MultiAgent Builder — pinned from a curated known-good map",
        "# (versions verified 2026-01; refresh periodically). Unpinned lines are",
        "# third-party imports with no known-good pin — verify before deploying.",
    ]
    for pkg in sorted(pinned):
        lines.append(f"{pkg}=={pinned[pkg]}")
    for pkg in sorted(set(unpinned)):
        lines.append(f"{pkg}  # unpinned: not in known-good map, verify version")
    return "\n".join(lines) + "\n", warnings


def render_config() -> str:
    return '''from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application settings, loaded from environment / .env."""

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    # SQLite by default; set DATABASE_URL to a Postgres URL in production, e.g.
    # postgresql+psycopg2://user:pass@host:5432/dbname
    database_url: str = "sqlite:///./app.db"
    cors_origins: str = "*"
    secret_key: str = "change-me-in-production"


settings = Settings()
'''


def render_database() -> str:
    return '''from collections.abc import Generator

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.config import settings

# SQLite needs check_same_thread=False for FastAPI's threaded request handling;
# a Postgres URL uses no special connect args.
_connect_args = (
    {"check_same_thread": False} if settings.database_url.startswith("sqlite") else {}
)
engine = create_engine(settings.database_url, connect_args=_connect_args, pool_pre_ping=True)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


class Base(DeclarativeBase):
    """Shared declarative base — every ORM model subclasses this."""


def get_db() -> Generator[Session, None, None]:
    """FastAPI dependency yielding a database session, closed after the request."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
'''


def _router_module(filepath: str) -> str:
    """`backend/app/routers/invoices.py` -> `app.routers.invoices`."""
    from .import_fixer import _module_of
    return _module_of(filepath) or ""


def render_main(project_name: str, router_filepaths: list) -> str:
    """Render main.py registering ONLY the given (successfully generated) routers.

    Each router module is expected to expose `router = APIRouter(...)`.
    """
    imports = []
    includes = []
    for fp in router_filepaths:
        mod = _router_module(fp)
        if not mod:
            continue
        alias = mod.replace(".", "_") + "_router"
        imports.append(f"from {mod} import router as {alias}")
        includes.append(f"app.include_router({alias})")

    imports_block = "\n".join(imports) if imports else "# (no routers were generated)"
    includes_block = "\n".join(includes) if includes else "# (no routers to register)"
    title = json.dumps(project_name or "Generated API")

    return f'''from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.config import settings
{imports_block}

app = FastAPI(title={title})

_origins = ["*"] if settings.cors_origins == "*" else [o.strip() for o in settings.cors_origins.split(",")]
app.add_middleware(
    CORSMiddleware,
    allow_origins=_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

{includes_block}


@app.get("/health", tags=["health"])
async def health():
    return {{"status": "ok"}}
'''
