import os
from dataclasses import dataclass, field
from pathlib import Path

from .code_cleaner import strip_code_fences

# Base directory where all generated project files land (project root / outputs)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
OUTPUTS_ROOT = os.path.join(PROJECT_ROOT, "outputs")


def get_header_comment(filepath: str) -> str:
    """
    Returns an appropriate header comment for the generated file,
    based on its extension. Reminds the user this file needs review.
    Some file types (JSON, YAML in certain contexts) can't have comments
    and are skipped.
    """
    ext = Path(filepath).suffix.lower()
    filename = Path(filepath).name.lower()

    comment_styles = {
        '.py':   "# Generated by MultiAgent Builder — review before deploying\n\n",
        '.js':   "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.jsx':  "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.ts':   "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.tsx':  "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.sql':  "-- Generated by MultiAgent Builder — review before deploying\n\n",
        '.yml':  "# Generated by MultiAgent Builder — review before deploying\n\n",
        '.yaml': "# Generated by MultiAgent Builder — review before deploying\n\n",
        '.md':   "<!-- Generated by MultiAgent Builder — review before deploying -->\n\n",
        '.sh':   "# Generated by MultiAgent Builder — review before deploying\n\n",
    }

    # JSON cannot have comments — skip header
    if ext == '.json':
        return ""
    # Dockerfile has no extension but supports # comments
    if filename == 'dockerfile':
        return "# Generated by MultiAgent Builder — review before deploying\n\n"
    # .env files support # comments
    if filename.startswith('.env'):
        return "# Generated by MultiAgent Builder — review before deploying\n\n"

    return comment_styles.get(ext, "")


def write_project_file(project_id: str, filepath: str, content: str, add_header: bool = True) -> dict:
    """
    Writes a generated file to outputs/{project_id}/{filepath}.
    Strips markdown code fences, adds a header comment, creates directories as needed.

    Returns a dict with: success, full_path, size_bytes, error (if any)
    """
    try:
        clean_content = strip_code_fences(content)

        if not clean_content.strip():
            return {
                "success": False,
                "full_path": None,
                "size_bytes": 0,
                "error": "Content was empty after stripping code fences"
            }

        header = get_header_comment(filepath) if add_header else ""
        final_content = header + clean_content

        full_path = os.path.join(OUTPUTS_ROOT, project_id, filepath)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)

        with open(full_path, "w", encoding="utf-8") as f:
            f.write(final_content)

        size_bytes = os.path.getsize(full_path)
        print(f"[FileWriter] Wrote {filepath} ({size_bytes} bytes)")

        return {
            "success": True,
            "full_path": full_path,
            "size_bytes": size_bytes,
            "error": None
        }

    except Exception as e:
        print(f"[FileWriter] ERROR writing {filepath}: {e}")
        return {
            "success": False,
            "full_path": None,
            "size_bytes": 0,
            "error": str(e)
        }


@dataclass
class ProcessedFile:
    """Result of processing one generated file — PURE data, no shared state.

    A worker (possibly on another thread) produces this; the coordinator turns
    it into a state mutation + broadcast via commit_generated_file. `content` is
    fence-stripped, header-free, and import-repaired: the exact form
    generated_files must store so state and disk stay in sync.
    """
    filepath: str
    content: str
    status: str  # "ok" | "failed"
    size_bytes: int = 0
    warnings: list = field(default_factory=list)         # JS syntax-sanity hints
    import_warnings: list = field(default_factory=list)  # unresolved Python imports
    error: str = None


def process_generated_file(project_id: str, task: dict, raw_output: str,
                           file_tree: list = None, apply_import_fixer: bool = False) -> ProcessedFile:
    """PURE with respect to shared state (Day 20, ponytail #2): strip fences ->
    JS syntax sanity -> [opt-in] Python import repair -> write THIS file's own
    unique path to disk. Returns a ProcessedFile. No generated_files/errors/log
    mutation, no broadcast — commit_generated_file (coordinator-only) does that.

    Safe to call from a worker thread: filepaths are unique per phase (Day 19
    single-owner assertion), so no two workers write the same path, and nothing
    here touches shared in-memory state. `file_tree` (the phase's planned file
    list) is passed in rather than read from a live, concurrently-mutated state
    dict.

    Validation + one-shot repair are NOT here — they need the LLM message
    context and stay one layer up in the coder's generate step (call_validated),
    under the worker's single concurrency permit so both LLM calls are covered.
    """
    filepath = task.get("filepath", "")
    clean = strip_code_fences(raw_output)
    # Day 22: real in-process parsers (ast/compile for .py, json/yaml for
    # artifacts) replace the Day 18 brace heuristic. Free, so it runs on every
    # file regardless of which agent produced it — including agents that do not
    # route through call_validated. JS/JSX is absent here on purpose: it needs a
    # node subprocess, batched post-phase in validation_pass.
    from ..validation.syntax import validate_content
    warnings = [i.describe() for i in validate_content(clean, filepath)]

    import_warnings = []
    if apply_import_fixer:
        from .import_fixer import fix_imports
        clean, import_warnings = fix_imports(clean, filepath, file_tree or [])

    result = write_project_file(project_id, filepath, clean)
    return ProcessedFile(
        filepath=filepath,
        content=clean,
        status="ok" if result["success"] else "failed",
        size_bytes=result["size_bytes"],
        warnings=warnings,
        import_warnings=import_warnings,
        error=result["error"],
    )


def commit_generated_file(state: dict, processed: ProcessedFile, *, project_id: str,
                          phase: str, counts: dict, event_type: str = "file_written",
                          extra: dict = None) -> None:
    """COORDINATOR-ONLY (Day 20, ponytail #2): fold one ProcessedFile into shared
    state and broadcast its lifecycle event. Runs on the single event loop that
    drives the scheduler, so all mutation is serialised — the parallel-worker
    class of bugs (lost updates, interleaved logs, double broadcasts) is
    eliminated by construction, not by locking.

    Updates state["generated_files"] (state == disk), appends any import warnings
    to state["errors"] as `import_warning:` entries (Gate 4 QA panel surfaces
    them), logs, and broadcasts `event_type` (file_written / file_failed /
    file_blocked) carrying the {done, failed, blocked, total} count snapshot so
    the frontend renders idempotently under reconnect/replay.
    """
    from ..core.connection_manager import manager

    state.setdefault("generated_files", {})[processed.filepath] = processed.content

    if processed.import_warnings:
        state.setdefault("errors", []).extend(
            f"import_warning: {w}" for w in processed.import_warnings)
    log = state.setdefault("log", [])
    if processed.warnings:
        log.append(f"coder: {processed.filepath} syntax warnings: {'; '.join(processed.warnings)}")
    verb = {"file_written": "wrote", "file_failed": "stubbed (failed)",
            "file_blocked": "stubbed (blocked)"}.get(event_type, "wrote")
    log.append(f"{phase}_coder: {verb} {processed.filepath} ({processed.size_bytes} bytes)")

    event = {
        "type": event_type,
        "filename": Path(processed.filepath).name,
        "filepath": processed.filepath,
        "phase": phase,
        **counts,
    }
    if extra:
        event.update(extra)
    manager.broadcast_sync(project_id, event)


def get_project_output_dir(project_id: str) -> str:
    """Returns the full path to a project's output directory, creating it if needed."""
    path = os.path.join(OUTPUTS_ROOT, project_id)
    os.makedirs(path, exist_ok=True)
    return path


def list_generated_files(project_id: str) -> list[dict]:
    """
    Returns a list of all files generated for a project so far.
    Each entry: {filepath (relative), size_bytes, extension}
    """
    project_dir = os.path.join(OUTPUTS_ROOT, project_id)
    if not os.path.exists(project_dir):
        return []

    files = []
    for root, _, filenames in os.walk(project_dir):
        for fname in filenames:
            full_path = os.path.join(root, fname)
            rel_path = os.path.relpath(full_path, project_dir)
            files.append({
                "filepath": rel_path.replace(os.sep, '/'),
                "size_bytes": os.path.getsize(full_path),
                "extension": Path(fname).suffix
            })
    return files