import os
import re
from pathlib import Path
from datetime import datetime

# Base directory where all generated project files land (project root / outputs)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
OUTPUTS_ROOT = os.path.join(PROJECT_ROOT, "outputs")


def strip_code_fences(code: str) -> str:
    """
    Remove markdown code fences that LLMs add despite instructions not to.
    Handles ```python, ```yaml, ```dockerfile, ```sql, plain ```, etc.
    """
    code = code.strip()
    code = re.sub(r'^```[a-zA-Z0-9_-]*\n?', '', code)
    code = re.sub(r'\n?```$', '', code)
    return code.strip()


def get_header_comment(filepath: str) -> str:
    """
    Returns an appropriate header comment for the generated file,
    based on its extension. Reminds the user this file needs review.
    Some file types (JSON, YAML in certain contexts) can't have comments
    and are skipped.
    """
    ext = Path(filepath).suffix.lower()
    filename = Path(filepath).name.lower()

    comment_styles = {
        '.py':   "# Generated by MultiAgent Builder — review before deploying\n\n",
        '.js':   "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.jsx':  "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.ts':   "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.tsx':  "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.sql':  "-- Generated by MultiAgent Builder — review before deploying\n\n",
        '.yml':  "# Generated by MultiAgent Builder — review before deploying\n\n",
        '.yaml': "# Generated by MultiAgent Builder — review before deploying\n\n",
        '.md':   "<!-- Generated by MultiAgent Builder — review before deploying -->\n\n",
        '.sh':   "# Generated by MultiAgent Builder — review before deploying\n\n",
    }

    # JSON cannot have comments — skip header
    if ext == '.json':
        return ""
    # Dockerfile has no extension but supports # comments
    if filename == 'dockerfile':
        return "# Generated by MultiAgent Builder — review before deploying\n\n"
    # .env files support # comments
    if filename.startswith('.env'):
        return "# Generated by MultiAgent Builder — review before deploying\n\n"

    return comment_styles.get(ext, "")


def write_project_file(project_id: str, filepath: str, content: str, add_header: bool = True) -> dict:
    """
    Writes a generated file to outputs/{project_id}/{filepath}.
    Strips markdown code fences, adds a header comment, creates directories as needed.

    Returns a dict with: success, full_path, size_bytes, error (if any)
    """
    try:
        clean_content = strip_code_fences(content)

        if not clean_content.strip():
            return {
                "success": False,
                "full_path": None,
                "size_bytes": 0,
                "error": "Content was empty after stripping code fences"
            }

        header = get_header_comment(filepath) if add_header else ""
        final_content = header + clean_content

        full_path = os.path.join(OUTPUTS_ROOT, project_id, filepath)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)

        with open(full_path, "w", encoding="utf-8") as f:
            f.write(final_content)

        size_bytes = os.path.getsize(full_path)
        print(f"[FileWriter] Wrote {filepath} ({size_bytes} bytes)")

        return {
            "success": True,
            "full_path": full_path,
            "size_bytes": size_bytes,
            "error": None
        }

    except Exception as e:
        print(f"[FileWriter] ERROR writing {filepath}: {e}")
        return {
            "success": False,
            "full_path": None,
            "size_bytes": 0,
            "error": str(e)
        }


def get_project_output_dir(project_id: str) -> str:
    """Returns the full path to a project's output directory, creating it if needed."""
    path = os.path.join(OUTPUTS_ROOT, project_id)
    os.makedirs(path, exist_ok=True)
    return path


def list_generated_files(project_id: str) -> list[dict]:
    """
    Returns a list of all files generated for a project so far.
    Each entry: {filepath (relative), size_bytes, extension}
    """
    project_dir = os.path.join(OUTPUTS_ROOT, project_id)
    if not os.path.exists(project_dir):
        return []

    files = []
    for root, _, filenames in os.walk(project_dir):
        for fname in filenames:
            full_path = os.path.join(root, fname)
            rel_path = os.path.relpath(full_path, project_dir)
            files.append({
                "filepath": rel_path.replace(os.sep, '/'),
                "size_bytes": os.path.getsize(full_path),
                "extension": Path(fname).suffix
            })
    return files