import os
from pathlib import Path

from .code_cleaner import strip_code_fences

# Base directory where all generated project files land (project root / outputs)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
OUTPUTS_ROOT = os.path.join(PROJECT_ROOT, "outputs")


def get_header_comment(filepath: str) -> str:
    """
    Returns an appropriate header comment for the generated file,
    based on its extension. Reminds the user this file needs review.
    Some file types (JSON, YAML in certain contexts) can't have comments
    and are skipped.
    """
    ext = Path(filepath).suffix.lower()
    filename = Path(filepath).name.lower()

    comment_styles = {
        '.py':   "# Generated by MultiAgent Builder — review before deploying\n\n",
        '.js':   "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.jsx':  "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.ts':   "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.tsx':  "// Generated by MultiAgent Builder — review before deploying\n\n",
        '.sql':  "-- Generated by MultiAgent Builder — review before deploying\n\n",
        '.yml':  "# Generated by MultiAgent Builder — review before deploying\n\n",
        '.yaml': "# Generated by MultiAgent Builder — review before deploying\n\n",
        '.md':   "<!-- Generated by MultiAgent Builder — review before deploying -->\n\n",
        '.sh':   "# Generated by MultiAgent Builder — review before deploying\n\n",
    }

    # JSON cannot have comments — skip header
    if ext == '.json':
        return ""
    # Dockerfile has no extension but supports # comments
    if filename == 'dockerfile':
        return "# Generated by MultiAgent Builder — review before deploying\n\n"
    # .env files support # comments
    if filename.startswith('.env'):
        return "# Generated by MultiAgent Builder — review before deploying\n\n"

    return comment_styles.get(ext, "")


def write_project_file(project_id: str, filepath: str, content: str, add_header: bool = True) -> dict:
    """
    Writes a generated file to outputs/{project_id}/{filepath}.
    Strips markdown code fences, adds a header comment, creates directories as needed.

    Returns a dict with: success, full_path, size_bytes, error (if any)
    """
    try:
        clean_content = strip_code_fences(content)

        if not clean_content.strip():
            return {
                "success": False,
                "full_path": None,
                "size_bytes": 0,
                "error": "Content was empty after stripping code fences"
            }

        header = get_header_comment(filepath) if add_header else ""
        final_content = header + clean_content

        full_path = os.path.join(OUTPUTS_ROOT, project_id, filepath)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)

        with open(full_path, "w", encoding="utf-8") as f:
            f.write(final_content)

        size_bytes = os.path.getsize(full_path)
        print(f"[FileWriter] Wrote {filepath} ({size_bytes} bytes)")

        return {
            "success": True,
            "full_path": full_path,
            "size_bytes": size_bytes,
            "error": None
        }

    except Exception as e:
        print(f"[FileWriter] ERROR writing {filepath}: {e}")
        return {
            "success": False,
            "full_path": None,
            "size_bytes": 0,
            "error": str(e)
        }


def js_syntax_sanity(content: str, filepath: str) -> list:
    """Cheap structural sanity for JS/JSX/TS files — NOT a parser.

    Returns a list of warning strings (empty = looks structurally OK). These
    are warnings, never fatal: brace/paren counting is naive about strings and
    comments, so a mismatch is a hint, not proof. Day 22 deep-validation
    (acorn AST parse, import resolution, endpoint cross-check) is the hook
    point that replaces these heuristics.
    """
    ext = Path(filepath).suffix.lower()
    if ext not in {'.js', '.jsx', '.ts', '.tsx', '.mjs'}:
        return []
    if not content.strip():
        return ["file is empty after cleaning"]

    warnings = []
    if content.count('{') != content.count('}'):
        warnings.append(f"unbalanced braces ({content.count('{')} open / {content.count('}')} close)")
    if content.count('(') != content.count(')'):
        warnings.append(f"unbalanced parens ({content.count('(')} open / {content.count(')')} close)")
    if 'import ' not in content and 'export ' not in content:
        warnings.append("no import or export statement — likely truncated or prose")
    return warnings


def process_and_write_generated_file(project_id: str, task: dict, raw_output: str, state: dict) -> dict:
    """Shared write-time chain for every coder agent (Day 18 frontend, Day 19
    backend, Day 20 parallel runner reuse it unchanged): strip fences ->
    JS syntax sanity -> write to disk. Returns a result dict the caller uses
    to update generated_files and broadcast.

    Deliberately message-agnostic: validation + one-shot repair stay in the
    agent (call_validated needs the LLM message context), and state-update +
    the file_written broadcast stay in the caller (per-phase index/total
    differ). See the Day 18 ponytail #3 conclusion.

    The returned `content` is fence-stripped and header-free — the exact form
    generated_files must store so state and disk stay in sync and the Gate-4
    clean_project_files pass is a no-op safety net rather than the mechanism.
    """
    filepath = task.get("filepath", "")
    log = state.get("log")

    clean = strip_code_fences(raw_output)
    warnings = js_syntax_sanity(clean, filepath)
    if warnings and log is not None:
        log.append(f"coder: {filepath} syntax warnings: {'; '.join(warnings)}")

    result = write_project_file(project_id, filepath, clean)
    return {
        "success": result["success"],
        "filepath": filepath,
        "content": clean,
        "size_bytes": result["size_bytes"],
        "warnings": warnings,
        "error": result["error"],
    }


def get_project_output_dir(project_id: str) -> str:
    """Returns the full path to a project's output directory, creating it if needed."""
    path = os.path.join(OUTPUTS_ROOT, project_id)
    os.makedirs(path, exist_ok=True)
    return path


def list_generated_files(project_id: str) -> list[dict]:
    """
    Returns a list of all files generated for a project so far.
    Each entry: {filepath (relative), size_bytes, extension}
    """
    project_dir = os.path.join(OUTPUTS_ROOT, project_id)
    if not os.path.exists(project_dir):
        return []

    files = []
    for root, _, filenames in os.walk(project_dir):
        for fname in filenames:
            full_path = os.path.join(root, fname)
            rel_path = os.path.relpath(full_path, project_dir)
            files.append({
                "filepath": rel_path.replace(os.sep, '/'),
                "size_bytes": os.path.getsize(full_path),
                "extension": Path(fname).suffix
            })
    return files