"""Deterministic React/Vite frontend infrastructure (2026-08-11).

The exact counterpart of backend_infra.py and node_infra.py, added because the
react-fastapi profile had no equivalent and the gap was load-bearing: across
every project ever generated by this system, **not one produced a
`frontend/package.json`**. The backend shipped a real `requirements.txt` (that
one IS deterministic) while the frontend shipped source files with no manifest,
no build config and no HTML entry — so `npm install` had nothing to read and the
app could not start. The profile's own verification target ran `npm ci` against
a file that never existed.

WHY DETERMINISTIC, not generated. Same argument as node_infra: a hallucinated
version breaks `npm install` for the entire project, and a wrong entry point
breaks everything at once. These files are boilerplate that must be exactly
right, so they come from templates and a curated version map.

WHY THIS OWNS THE STYLESHEET. `prompts/frontend_coder_agent.md` instructs the
coder: *"NEVER import a stylesheet. There are no .css files in this project."*
That is a sound rule for component files, but it means nothing in the generated
set can ever wire Tailwind up. If this module does not write the CSS entry and
import it from `main.jsx`, every utility class the coder emits renders as
nothing — a project that looks broken while every file is individually correct.

TAILWIND IS PINNED TO v3, deliberately, against the registry's `latest`.
npm's `latest` is 4.3.3, but v4 renamed a swathe of utilities and dropped the
config/PostCSS setup. Generated components are written from v3-era conventions,
and in v4 an unrecognised utility does not error — it silently renders unstyled.
A silent styling failure is the worst possible outcome for the thing a user
judges first. Tailwind publishes a `v3-lts` dist-tag (3.4.19), so this is a
supported line, not an abandoned one. Revisit when the coder prompt is updated
to v4 conventions and the two can move together.
"""
import json
import re

# Curated known-good, real, installable versions.
#
# VERIFIED 2026-08-11 against registry.npmjs.org — every pin below was read from
# the registry on that date rather than recalled, because a confident wrong
# version is exactly the failure this module exists to prevent.
#
# ponytail: hand-maintained map on the same refresh cadence as
# node_infra.KNOWN_GOOD_VERSIONS and backend_infra.KNOWN_GOOD_VERSIONS.
KNOWN_GOOD_VERSIONS = {
    # Core runtime
    "react": "^19.2.8",
    "react-dom": "^19.2.8",
    "axios": "^1.19.0",
    "react-router-dom": "^7.18.2",
    # Build toolchain (devDependencies)
    "vite": "^8.2.1",
    "@vitejs/plugin-react": "^6.0.5",
    "tailwindcss": "^3.4.19",        # v3-lts on purpose — see module docstring
    "postcss": "^8.5.26",
    "autoprefixer": "^10.5.4",
    # Commonly reached for by a CRM-shaped app
    "@tanstack/react-query": "^5.101.4",
    "@tanstack/react-table": "^9.1.2",
    "react-hook-form": "^7.85.0",
    "zod": "^4.4.3",
    "recharts": "^3.10.1",
    "chart.js": "^4.5.1",
    "react-chartjs-2": "^5.3.1",
    "date-fns": "^4.4.0",
    "dayjs": "^1.11.21",
    "clsx": "^2.1.1",
    "classnames": "^2.5.1",
    "lucide-react": "^1.31.0",
    "react-icons": "^5.7.0",
    "@heroicons/react": "^2.2.0",
    "@headlessui/react": "^2.2.10",
    "react-hot-toast": "^2.6.0",
    "zustand": "^5.0.14",
    "framer-motion": "^13.1.0",
    "uuid": "^14.0.1",
    "papaparse": "^5.5.4",
}

# Always present regardless of what the generated files import: without these
# there is no app at all.
_ALWAYS = ["react", "react-dom", "axios"]
_DEV_ALWAYS = ["vite", "@vitejs/plugin-react", "tailwindcss", "postcss", "autoprefixer"]

_IMPORT_RE = re.compile(
    r"""(?:\bfrom\s*|\bimport\s*\(?\s*|\brequire\s*\(\s*)['"]([^'"]+)['"]""")

_SOURCE_SUFFIXES = (".js", ".jsx", ".mjs", ".ts", ".tsx")


def _bare_specifiers(code: str) -> set:
    """Third-party package names imported by one file (best effort).

    ponytail: regex, matching the policy already set by node_infra and
    validation/syntax.py — a real parse lives in the node subprocess, and
    shipping its AST back to walk in Python costs more than "list the
    specifiers" is worth.
    """
    names = set()
    for spec in _IMPORT_RE.findall(code or ""):
        if spec.startswith((".", "/")) or spec.startswith("node:"):
            continue
        # A CSS or asset import is not an npm dependency.
        if spec.endswith((".css", ".svg", ".png", ".jpg", ".json")):
            continue
        parts = spec.split("/")
        names.add("/".join(parts[:2]) if spec.startswith("@") else parts[0])
    return names


def render_package_json(project_name: str, generated_files: dict) -> tuple:
    """Deterministically render frontend/package.json. Returns (content, warnings).

    Core stack always pinned. Third-party imports found across the generated
    frontend files are pinned from KNOWN_GOOD_VERSIONS; anything unknown is
    recorded as a warning and left OUT rather than pinned to a fabricated
    version — an invented version fails the install for the whole project, which
    is strictly worse than one missing dependency the warning names by hand.
    """
    imports = set()
    for path, content in (generated_files or {}).items():
        if path.startswith("frontend/") and path.endswith(_SOURCE_SUFFIXES):
            imports |= _bare_specifiers(content)

    warnings = []
    deps = {pkg: KNOWN_GOOD_VERSIONS[pkg] for pkg in _ALWAYS}
    for name in sorted(imports):
        if name in deps or name in _DEV_ALWAYS:
            continue
        if name in KNOWN_GOOD_VERSIONS:
            deps[name] = KNOWN_GOOD_VERSIONS[name]
        else:
            warnings.append(
                f"package.json: `{name}` is imported by generated frontend code "
                f"but is not in the known-good version map — NOT added as a "
                f"dependency; add it with a verified version before running "
                f"npm install")

    safe_name = re.sub(r"[^a-z0-9._-]+", "-",
                       (project_name or "generated-app").lower()).strip("-")
    pkg = {
        "name": (safe_name or "generated-app") + "-frontend",
        "private": True,
        "version": "1.0.0",
        # Vite requires ESM for the config file, and every generated component
        # uses import/export.
        "type": "module",
        "scripts": {
            "dev": "vite",
            "build": "vite build",
            "preview": "vite preview",
        },
        "dependencies": dict(sorted(deps.items())),
        "devDependencies": {p: KNOWN_GOOD_VERSIONS[p] for p in sorted(_DEV_ALWAYS)},
    }
    return json.dumps(pkg, indent=2) + "\n", warnings


def render_vite_config() -> str:
    """Vite config with the dev proxy the generated axios client depends on.

    The coder is told to call the API at `/api/...` on the same origin. In
    development the Vite server is a different port from FastAPI, so without
    this proxy every request 404s against the dev server — code that is correct
    in production and broken the moment anyone runs `npm run dev`.
    """
    return '''import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// The generated axios client calls same-origin `/api/...`. In dev the Vite
// server and FastAPI are different ports, so these proxies are what make that
// work without the client needing to know a base URL.
export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: {
      '/api': { target: 'http://localhost:8000', changeOrigin: true },
      '/ws': { target: 'ws://localhost:8000', ws: true },
    },
  },
  build: { outDir: 'dist', sourcemap: true },
});
'''


def render_index_html(project_name: str) -> str:
    """The HTML entry. Vite treats index.html as the build entry point, so
    without it `vite build` fails outright — there is nothing to build."""
    title = (project_name or "Generated App").strip()
    # Escaped: a project name is user input and lands inside an element.
    for bad, good in (("&", "&amp;"), ("<", "&lt;"), (">", "&gt;")):
        title = title.replace(bad, good)
    return f'''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
'''


def render_tailwind_config() -> str:
    """v3-style config. `content` must cover every generated component or
    Tailwind purges the classes they use and the build ships unstyled."""
    return '''/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: { extend: {} },
  plugins: [],
};
'''


def render_postcss_config() -> str:
    return '''export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
'''


def render_index_css() -> str:
    """The only stylesheet in the project. The coder prompt forbids generating
    or importing one, so if this module does not write it, nothing does and
    every utility class in every component renders as no styling at all."""
    return '''@tailwind base;
@tailwind components;
@tailwind utilities;
'''


def render_main_jsx(app_import: str = "./App.jsx") -> str:
    """React entry point, mounting into the #root that index.html provides and
    importing the one stylesheet that turns Tailwind on."""
    return f'''import React from 'react';
import ReactDOM from 'react-dom/client';
import App from '{app_import}';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
'''


def render_fallback_app() -> str:
    """Used ONLY when the coder produced no App component at all.

    Deliberately states that generation was incomplete rather than rendering a
    convincing empty shell: a plausible-looking placeholder is how a failed run
    gets mistaken for a working one.
    """
    return '''export default function App() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-50">
      <div className="max-w-md rounded-lg border border-amber-300 bg-amber-50 p-6">
        <h1 className="text-lg font-semibold text-amber-900">
          Frontend generation was incomplete
        </h1>
        <p className="mt-2 text-sm text-amber-800">
          No application component was generated for this project, so this
          placeholder was written in its place. Check docs/qa-report.md and
          docs/validation-report.md for what failed.
        </p>
      </div>
    </div>
  );
}
'''
