"""Deterministic Node/Express infrastructure files (Improvement 03, Phase 3).

The exact counterpart of backend_infra.py, for the same reason: package.json,
the shared Prisma client, and the server entrypoint are boilerplate that MUST be
correct. A hallucinated npm version breaks `npm ci` for the whole project, a
second `new PrismaClient()` exhausts the Postgres connection pool, and a wrong
entrypoint breaks every request. So these are rendered from hand-maintained
templates and a curated version map, NOT generated by the LLM.

Ownership mirrors react-fastapi: this module owns the JS infra, the DevOps
agent keeps Docker/CI, and the coder owns routes/services/schema. server.js is
derived from the ACTUAL generated route files, so a route that failed to
generate is never mounted.
"""
import json
import re

# Curated known-good, real, installable versions. The LLM never invents a
# version — a confident hallucinated pin fails `npm ci` for the entire project.
#
# ponytail: hand-maintained map, refresh periodically — same policy and the same
# refresh cadence as KNOWN_GOOD_VERSIONS in backend_infra.py.
# Verified as of 2026-01.
KNOWN_GOOD_VERSIONS = {
    "express": "^4.21.2",
    "@prisma/client": "^6.2.1",
    "prisma": "^6.2.1",
    "cors": "^2.8.5",
    "dotenv": "^16.4.7",
    "helmet": "^8.0.0",
    "morgan": "^1.10.0",
    "zod": "^3.24.1",
    "jsonwebtoken": "^9.0.2",
    "bcryptjs": "^2.4.3",
}

# Always required regardless of what the generated files import.
_ALWAYS = ["express", "@prisma/client", "cors", "dotenv"]
_DEV_ALWAYS = ["prisma"]

# Node builtins, so they are never mistaken for npm packages.
_BUILTINS = {
    "assert", "buffer", "child_process", "crypto", "events", "fs", "http",
    "https", "os", "path", "process", "stream", "string_decoder", "timers",
    "url", "util", "zlib", "worker_threads", "readline", "net", "dns",
}

_IMPORT_RE = re.compile(
    r"""(?:\bfrom\s*|\bimport\s*\(?\s*|\brequire\s*\(\s*)['"]([^'"]+)['"]""")


def _bare_specifiers(code: str) -> set:
    """Third-party package names imported by one JS file (best effort).

    ponytail: regex, matching the policy already set in validation/syntax.py —
    a real parse lives in the node subprocess and shipping its AST back to walk
    in Python costs more than "list the specifiers" is worth.
    """
    names = set()
    for spec in _IMPORT_RE.findall(code or ""):
        if spec.startswith((".", "/")):
            continue
        if spec.startswith("node:"):
            continue
        parts = spec.split("/")
        pkg = "/".join(parts[:2]) if spec.startswith("@") else parts[0]
        if pkg in _BUILTINS:
            continue
        names.add(pkg)
    return names


def render_package_json(project_name: str, generated_files: dict) -> tuple:
    """Deterministically render package.json. Returns (content, warnings).

    Core stack always pinned. Third-party imports detected across generated
    files are pinned from KNOWN_GOOD_VERSIONS; anything unknown is recorded as
    a warning and left OUT rather than pinned to a fabricated version — an
    invented version fails `npm ci` for the whole project, which is worse than
    a missing dependency the warning names.
    """
    imports = set()
    for path, content in (generated_files or {}).items():
        if path.endswith((".js", ".mjs")):
            imports |= _bare_specifiers(content)

    warnings = []
    deps = {pkg: KNOWN_GOOD_VERSIONS[pkg] for pkg in _ALWAYS}
    for name in sorted(imports):
        if name in deps or name in _DEV_ALWAYS:
            continue
        if name in KNOWN_GOOD_VERSIONS:
            deps[name] = KNOWN_GOOD_VERSIONS[name]
        else:
            warnings.append(
                f"package.json: `{name}` is imported by generated code but is "
                f"not in the known-good version map — NOT added as a "
                f"dependency; add it with a verified version before running "
                f"npm ci")

    safe_name = re.sub(r"[^a-z0-9._-]+", "-", (project_name or "generated-api").lower()).strip("-")
    pkg = {
        "name": safe_name or "generated-api",
        "version": "1.0.0",
        "private": True,
        # The coder prompt mandates ES modules and `.js` import extensions;
        # without this line every one of those imports is a syntax error.
        "type": "module",
        "engines": {"node": ">=20"},
        "scripts": {
            "start": "node src/server.js",
            "dev": "node --watch src/server.js",
            "prisma:generate": "prisma generate",
            "prisma:migrate": "prisma migrate dev",
        },
        "dependencies": dict(sorted(deps.items())),
        "devDependencies": {p: KNOWN_GOOD_VERSIONS[p] for p in _DEV_ALWAYS},
    }
    return json.dumps(pkg, indent=2) + "\n", warnings


def render_prisma_client() -> str:
    """The ONE shared Prisma client. The coder prompt forbids constructing
    another; this is the module it must import."""
    return '''import { PrismaClient } from '@prisma/client';

// One client for the whole process. Each PrismaClient opens its own connection
// pool, so constructing one per module exhausts Postgres' connection limit.
// In development, `node --watch` re-imports modules on every change, which
// would leak a pool per reload — so the instance is stashed on globalThis.
const globalForPrisma = globalThis;

export const prisma =
  globalForPrisma.__prisma ?? new PrismaClient({ log: ['warn', 'error'] });

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.__prisma = prisma;
}
'''


def _route_mount(filepath: str) -> tuple:
    """(import path, mount path, identifier) for a generated route file.

    `src/routes/parcels.js` -> ('./routes/parcels.js', '/parcels', 'parcelsRouter')
    """
    stem = filepath.rsplit("/", 1)[-1]
    if stem.endswith(".js"):
        stem = stem[:-3]
    for suffix in ("_routes", "_router", ".routes", ".router"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
    ident = re.sub(r"[^a-zA-Z0-9]+", " ", stem).title().replace(" ", "")
    ident = (ident[:1].lower() + ident[1:]) if ident else "resource"
    rel = filepath
    if rel.startswith("src/"):
        rel = rel[len("src/"):]
    return f"./{rel}", f"/{stem.replace('_', '-')}", f"{ident}Router"


def render_server(project_name: str, route_filepaths: list) -> str:
    """Render src/server.js mounting ONLY the given (successfully generated)
    routes, plus the error middleware every async handler's next(err) needs."""
    imports, mounts = [], []
    for fp in route_filepaths:
        spec, mount, ident = _route_mount(fp)
        imports.append(f"import {ident} from '{spec}';")
        mounts.append(f"app.use('/api{mount}', {ident});")

    imports_block = "\n".join(imports) if imports else "// (no routes were generated)"
    mounts_block = "\n".join(mounts) if mounts else "// (no routes to mount)"
    title = json.dumps(project_name or "Generated API")

    return f'''import express from 'express';
import cors from 'cors';
import 'dotenv/config';

{imports_block}

const app = express();

app.use(cors({{ origin: process.env.CORS_ORIGIN ?? '*' }}));
app.use(express.json());

app.get('/health', (req, res) => {{
  res.json({{ status: 'ok', service: {title} }});
}});

{mounts_block}

// 404 for anything unmatched — before the error handler, after every route.
app.use((req, res) => {{
  res.status(404).json({{ error: 'Not found' }});
}});

// Error middleware. Express identifies it by its FOUR parameters, so `next`
// must stay in the signature even though it is unused — dropping it silently
// turns this into an ordinary middleware and every next(err) becomes a hang.
// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {{
  console.error(err);
  res.status(err.status ?? 500).json({{ error: 'Internal server error' }});
}});

const port = Number(process.env.PORT) || 3000;
app.listen(port, () => {{
  console.log(`Listening on port ${{port}}`);
}});

export default app;
'''
