"""The docs/ mirror: every designing agent's output shipped beside the code.

Zero API calls — each stage's result dict is a fixture, because what is under
test is the mirroring, not the agents.
"""
import json
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.graph import pipeline as P                                # noqa: E402
from app.utils.file_writer import OUTPUTS_ROOT                     # noqa: E402

PID = "test-stage-docs"
DOCS = os.path.join(OUTPUTS_ROOT, PID, "docs")

FIXTURES = {
    "research": {"research_report": "# Research\n\nCRM prior art.",
                 "tech_stack": '{"frontend":"React"}'},
    "requirements": {"requirements_doc": "# Requirements\n\nFR-1."},
    "architecture": {"architecture_doc": "# Architecture\n\nComponents."},
    "planning": {"implementation_plan": '{"tasks":[{"id":"t1"}]}',
                 "ui_contract": "# UI Contract\n\nSpacing.",
                 "excluded_tasks": [{"id": "t9", "reason": "out of scope"}]},
    "validation": {"validation_report": {"counts": {"files": 3}}},
    "qa": {"qa_report": "# QA\n\nClean."},
    "build_verify": {"build_verification": {"frontend": {"build": "ok"}}},
}


def _clean():
    shutil.rmtree(os.path.join(OUTPUTS_ROOT, PID), ignore_errors=True)


def _write_all():
    _clean()
    for stage, result in FIXTURES.items():
        P._persist_stage_doc(stage, PID, result)


def _read(name):
    with open(os.path.join(DOCS, name)) as fh:
        return fh.read()


# ── coverage ─────────────────────────────────────────────────────────────────

def test_every_designing_stage_contributes_a_document():
    """The agents that DESIGN the project — not the coders, which produce the
    source itself — each leave their reasoning behind in docs/."""
    _write_all()
    written = set(os.listdir(DOCS))
    for stage, specs in P.STAGE_DOCS.items():
        for _, filename, _ in specs:
            assert filename in written, f"{stage} did not write {filename}"
    _clean()


def test_documented_stages_are_real_pipeline_nodes():
    """Drift guard: a doc entry for a stage that no longer exists would silently
    never fire, and nothing else would notice."""
    nodes = set(P.workflow.nodes)
    for stage in P.STAGE_DOCS:
        assert stage in nodes, f"STAGE_DOCS references '{stage}', not a node"


def test_filenames_are_unique_across_stages():
    """Two stages writing one filename means the later silently overwrites the
    earlier — a lost document, with no error anywhere."""
    seen = {}
    for stage, specs in P.STAGE_DOCS.items():
        for _, filename, _ in specs:
            assert filename not in seen, (
                f"{filename} written by both {seen.get(filename)} and {stage}")
            seen[filename] = stage


# ── rendering ────────────────────────────────────────────────────────────────

def test_structured_documents_have_balanced_fences():
    """The regression this suite exists for. write_project_file strips code
    fences by default, which ate the CLOSING fence of every generated
    implementation-plan.md from 2026-08-05 until this was fixed, leaving
    markdown with an unterminated code block."""
    _write_all()
    for name in ("implementation-plan.md", "tech-stack.md", "excluded-tasks.md",
                 "validation-report.md", "build-verification.md"):
        body = _read(name)
        assert body.count("```") % 2 == 0, f"{name} has an unclosed code fence"
        assert body.rstrip().endswith("```"), f"{name} does not close its fence"
    _clean()


def test_structured_documents_are_valid_readable_json():
    _write_all()
    body = _read("implementation-plan.md")
    inner = body.split("```json\n", 1)[1].rsplit("\n```", 1)[0]
    assert json.loads(inner) == {"tasks": [{"id": "t1"}]}
    assert "\n" in inner, "JSON was not re-indented — a one-line plan is unreadable"
    _clean()


def test_prose_is_written_verbatim_with_no_generated_by_header():
    """These are documents a person reads, not source files to be reviewed
    before deploying, so the code header would just be noise at the top."""
    _write_all()
    assert _read("research.md") == FIXTURES["research"]["research_report"]
    assert "Generated by MultiAgent Builder" not in _read("architecture.md")
    _clean()


def test_a_stage_that_produced_nothing_writes_no_file():
    """Absence is information: a missing doc means that stage did not run.
    A placeholder would erase that signal."""
    _clean()
    P._persist_stage_doc("research", PID, {"research_report": "", "tech_stack": None})
    assert not os.path.isdir(DOCS)
    _clean()


def test_readme_index_appears_only_once_a_document_exists():
    _clean()
    P._persist_stage_doc("qa", PID, {"qa_report": ""})
    assert not os.path.isdir(DOCS)
    P._persist_stage_doc("qa", PID, {"qa_report": "# QA\n\nfine"})
    assert "README.md" in os.listdir(DOCS)
    _clean()


def test_readme_lists_every_document_the_pipeline_can_write():
    _write_all()
    readme = _read("README.md")
    for stage, specs in P.STAGE_DOCS.items():
        for _, filename, _ in specs:
            assert f"`{filename}`" in readme, f"README does not mention {filename}"
    _clean()


# ── safety ───────────────────────────────────────────────────────────────────

def test_an_unrenderable_field_never_fails_the_stage():
    """A documentation write must not be able to fail a run that has already
    produced its artifacts."""
    _clean()

    class Hostile:
        def __bool__(self):
            raise RuntimeError("boom")

    P._persist_stage_doc("validation", PID, {"validation_report": Hostile()})
    _clean()


def test_unknown_stage_and_missing_project_id_are_no_ops():
    _clean()
    P._persist_stage_doc("frontend_code", PID, {"generated_files": {"a.js": "x"}})
    P._persist_stage_doc("research", "", {"research_report": "# hi"})
    assert not os.path.isdir(os.path.join(OUTPUTS_ROOT, PID))
    _clean()


def test_docs_live_beside_the_code_so_the_zip_ships_them():
    """The export walks the output directory, so docs/ needs no export change —
    it just has to be written under the project root."""
    _write_all()
    root = os.path.join(OUTPUTS_ROOT, PID)
    assert os.path.isdir(os.path.join(root, "docs"))
    assert os.path.relpath(DOCS, root) == "docs"
    _clean()


if __name__ == "__main__":
    passed = failed = 0
    for name, fn in sorted(globals().items()):
        if not name.startswith("test_") or not callable(fn):
            continue
        try:
            fn()
            print(f"  ok   {name}")
            passed += 1
        except Exception as e:                  # noqa: BLE001
            print(f"  FAIL {name}: {type(e).__name__}: {e}")
            failed += 1
        finally:
            _clean()
    print(f"\n{passed} passed, {failed} failed. (0 API calls)")
    sys.exit(1 if failed else 0)
