import json
from pathlib import Path
from ..llm_router import call_llm
from ..utils.file_writer import write_project_file

SYSTEM_PROMPT = (Path(__file__).resolve().parents[3] / "prompts" / "devops_agent.md").read_text(encoding="utf-8")

# Audited 2026-08-03: NO real pipeline history; standalone dev-script calls
# measured <= 64. Direct model, generous headroom — truncation flag + failover
# accounting are the alarm.
DEVOPS_MAX_TOKENS = 2000

# DevOps files are generated as a fixed set, not from the task plan,
# because every project needs these regardless of what the planner decided
DEVOPS_FILES = [
    {
        "filepath": "Dockerfile",
        "description": "Multi-stage Dockerfile for the backend service. Python base image matching the tech stack, non-root user, proper layer caching (copy requirements.txt first, install, then copy code), expose the correct port, correct CMD to run the app."
    },
    {
        "filepath": "frontend/Dockerfile",
        "description": "Multi-stage Dockerfile for the frontend. Node build stage, nginx-alpine serve stage. Build the app then serve the static files."
    },
    {
        "filepath": "docker-compose.yml",
        "description": "Docker Compose file with backend, frontend, and database services (matching the tech stack's database choice). Include healthchecks, named volumes for data persistence, and environment variable references from .env."
    },
    {
        "filepath": "frontend/nginx.conf",
        "description": "Nginx config that proxies /api/ and /ws/ to the backend service, serves frontend static files, handles SPA routing with try_files, and enables gzip compression."
    },
    {
        "filepath": ".github/workflows/ci.yml",
        "description": "GitHub Actions CI workflow with steps for: install dependencies, lint, run tests, build. Trigger on push and pull_request to main branch."
    },
    {
        "filepath": ".env.example",
        "description": "Template environment file listing every environment variable the application needs, with descriptive comments explaining each one, and no real secret values (use placeholder text like 'your_key_here')."
    },
    {
        "filepath": "README.md",
        "description": "Project README with: project title and one-line description, prerequisites, setup instructions (clone, configure .env, docker compose up), development workflow notes, and a note that this project was generated by an AI multi-agent pipeline and should be reviewed before production use."
    },
]


def devops_agent(state: dict) -> dict:
    """
    DevOps Agent — Phase 4 Code Generation

    Reads: state['tech_stack'], state['project_name'], state['architecture_doc']
    Writes: state['devops_files'], state['generated_files'] (merged), state['log']

    Uses Groq Llama 3.3 70B — fast, good for config/YAML/Dockerfile generation.
    Generates a fixed set of infrastructure files regardless of the task plan,
    since every project needs these for deployment.
    """
    tech_stack_str = state.get("tech_stack", "")
    project_name = state.get("project_name", "Unknown Project")
    architecture_doc = state.get("architecture_doc", "")
    project_id = state.get("project_id", "")
    fast_mode = bool(state.get("fast_mode"))
    generated_files = state.get("generated_files", {})
    devops_files = state.get("devops_files", {})
    log = state.get("log", [])
    errors = state.get("errors", [])

    print(f"[DevOpsAgent] Starting for project: {project_name}")
    log.append("devops_agent: started")

    # ── Format tech stack for context ───────────────────────────────
    tech_stack_formatted = "Frontend: React + Vite\nBackend: FastAPI (Python)\nDatabase: PostgreSQL"
    key_libraries = []
    if tech_stack_str:
        try:
            stack = json.loads(tech_stack_str)
            tech_stack_formatted = (
                f"Frontend: {stack.get('frontend', 'React + Vite')}\n"
                f"Backend: {stack.get('backend', 'FastAPI (Python)')}\n"
                f"Database: {stack.get('database', 'PostgreSQL')}\n"
                f"Auth: {stack.get('auth', 'JWT')}\n"
                f"Hosting: {stack.get('hosting', 'Docker')}"
            )
            key_libraries = stack.get('key_libraries', [])
        except Exception:
            pass

    # ── Extract environment variables section if present ───────────
    env_vars_context = ""
    if "## Environment Variables" in architecture_doc:
        start = architecture_doc.find("## Environment Variables")
        env_vars_context = architecture_doc[start:start+1500]

    files_written = 0
    files_failed = 0

    # ── Generate each devops file ────────────────────────────────────
    for i, file_spec in enumerate(DEVOPS_FILES):
        filepath = file_spec["filepath"]
        description = file_spec["description"]

        print(f"[DevOpsAgent] Generating {filepath}...")

        user_content = f"""PROJECT NAME: {project_name}

TECH STACK:
{tech_stack_formatted}

KEY LIBRARIES: {', '.join(key_libraries) if key_libraries else 'Standard libraries for the stack'}

ENVIRONMENT VARIABLES CONTEXT:
{env_vars_context if env_vars_context else 'No specific environment variables identified — use standard variables for the tech stack (DATABASE_URL, JWT_SECRET, API keys as needed).'}

FILE TO GENERATE: {filepath}
DESCRIPTION: {description}

Generate the complete file content now. Output ONLY the raw file content — no explanation, no markdown fences, no preamble."""

        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_content}
        ]

        try:
            content = call_llm(messages, "devops", max_tokens=DEVOPS_MAX_TOKENS,
                               project_id=project_id, label=filepath,
                               fast_mode=fast_mode)

            if len(content.strip()) < 20:
                messages.append({"role": "assistant", "content": content})
                messages.append({
                    "role": "user",
                    "content": "Your response was too short. Generate the complete file content now."
                })
                content = call_llm(messages, "devops", max_tokens=DEVOPS_MAX_TOKENS,
                               project_id=project_id, label=filepath,
                               fast_mode=fast_mode)

            result = write_project_file(project_id, filepath, content)

            if result["success"]:
                devops_files[filepath] = content
                generated_files[filepath] = content
                files_written += 1
                log.append(f"devops_agent: wrote {filepath} ({result['size_bytes']} bytes)")

                from ..core.connection_manager import manager
                manager.broadcast_sync(project_id, {
                    "type": "file_written",
                    "filename": Path(filepath).name,
                    "filepath": filepath,
                    "phase": "devops",
                    "progress": f"{i+1}/{len(DEVOPS_FILES)}"
                })
            else:
                files_failed += 1
                errors.append(f"devops_agent: failed to write {filepath}: {result['error']}")

        except Exception as e:
            files_failed += 1
            error_msg = f"devops_agent: LLM call failed for {filepath}: {e}"
            errors.append(error_msg)
            print(f"[DevOpsAgent] ERROR: {error_msg}")

    # ── Fence cleanup pass before gate 4 ─────────────────────────────
    # State holds raw LLM output while disk got the stripped version at write
    # time; this pass makes state, disk, and the eventual ZIP identical.
    from ..utils.code_cleaner import clean_project_files
    generated_files, cleaned_count = clean_project_files(project_id, generated_files)
    devops_files = {k: generated_files.get(k, v) for k, v in devops_files.items()}
    log.append(f"devops_agent: fence cleanup pass — {cleaned_count} files cleaned")
    print(f"[DevOpsAgent] Cleanup pass: {cleaned_count} files cleaned")

    # Day 22: devops runs AFTER the validation node, so its JSON/YAML is checked
    # (and repaired within the same budget) here — otherwise docker-compose.yml
    # and the CI configs would be the only files that ship unparsed.
    from .validation_pass import validate_devops_artifacts
    artifact_update = validate_devops_artifacts({
        **state, "generated_files": generated_files, "devops_files": devops_files,
        "log": log, "errors": errors,
    })
    if artifact_update:
        generated_files = artifact_update["generated_files"]
        devops_files = artifact_update["devops_files"]

    log.append(f"devops_agent: completed — {files_written} files written, {files_failed} failed")
    print(f"[DevOpsAgent] Done. {files_written} written, {files_failed} failed")

    from ..core.connection_manager import manager
    manager.broadcast_sync(project_id, {
        "type": "agent_complete",
        "agent": "devops",
        "stage": "devops",
        "output_preview": f"Generated {files_written} infrastructure files",
        "files_written": files_written,
        "files_failed": files_failed
    })

    return {
        "generated_files": generated_files,
        "devops_files": devops_files,
        **{k: v for k, v in (artifact_update or {}).items()
           if k in ("validation_report", "retry_counts")},
        "log": log,
        "errors": errors,
        # current_stage names the NEXT stage: devops is the last node before the
        # final review gate. ("qa" here was stale — qa now runs before devops.)
        "current_stage": "human_gate_4",
        "_agent_event": True
    }